export interface ImageType {
  id: number; // Gets generated by the backend.
  src: string;
  fileName?: string;
  filePath?: string;
  uploadDate?: Date; // ISO 8601 format from LocalDateTime.
  fileSize?: number;
}
